---
title: "Git 심화"
description:  "Git 심화"
author: "RPythonStudyGroup feat. ChatGPT"
date: "2024-12-19"
date-modified: "2024-12-19"
categories: [Git]
---

### 커밋합치기

``` bash
git commit --amend
```
- `--amend` 옵션은 마지막 커밋을 수정하거나 새로운 변경사항을 기존 커밋에 추가할 때 사용됩니다.
- 작업 중 여러 번 커밋한 내용을 정리하거나, 작은 실수를 바로잡아 깔끔한 히스토리를 유지할 수 있습니다.
- 기존 커밋의 정보를 덮어씌우기 때문에, 원격 저장소에 이미 푸시한 커밋을 수정할 경우 협업 중인 팀원과의 충돌이 발생할 수 있습니다. 수정 후에는 git push --force가 필요합니다.


::: {.callout-note title="1단계: `Quarto Website` 프로젝트 만들기" collapse="true" appearance="minimal"}
-   RStudio/File 메뉴에서 `New Project...` 메뉴 선택
-   `New Directory`에 생성되도록 선택
-   Project type은 `Quarto Website`를 선택
-   상위폴더가 `C:/Projects`인지 확인 (=Global Options 사전 지정값)
-   Directory name은 `R-4.4.1-Quarto_Website_Example`로 지정
-   [x] Create a git repository: 체크 유지하여 버전관리 적용
-   [x] Use renv with this project: 체크 유지하여 패키지 독립관리 적용
-   [x] Use visual markdown editor: 체크 유지하여 wizwig 에디터 사용
-   [ ] Open in new session: 기존 프로젝트가 이미 열려있고, 같이 사용할려면 체크
:::

툴팁은 [`특정문자`]{.text-primary data-bs-toggle="tooltip" data-bs-html="true" data-bs-placement="bottom" title="1열<br> 2열"}이 구현되어야 한다.

```{r project_name, eval=FALSE, filename="recommeded project name"}
R-4.4.1-Hands_on_Shinylive_Example
```

-   폴더구조 참조

::: {#fig-ProjectDirectory}
```         
C:\Projects\
      └─ R-x.y.z-Project_Name
```

Recommended nomenclautue for Project directory name
:::

### 목적

-   QUarto Website 프로젝트를 생성하고 Bootstrap tooltip 및 Utterance 기능구현을 위한 설정, Render 기능을 위한 기본적인 R 패키지 설치까지를 template화 함.
